---

- name: Configure /etc/default/ufw
  ansible.builtin.template:
    src: etc/default/ufw.j2
    dest: /etc/default/ufw
    owner: root
    group: root
    mode: "0644"
  when: ufw.default is defined

- name: Configure /etc/ufw/before.rules
  ansible.builtin.template:
    src: etc/ufw/before.rules.j2
    dest: /etc/ufw/before.rules
    owner: root
    group: root
    mode: "0640"
  notify:
    - Restart ufw
  when: ufw.before_rules is defined

- name: Configure /etc/ufw/sysctl.conf
  ansible.builtin.template:
    src: etc/ufw/sysctl.conf.j2
    dest: /etc/ufw/sysctl.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart ufw
  when: ufw.sysctl is defined

- name: Set ufw rules
  community.general.ufw:
    rule: "{{ item.rule }}"
    interface: "{{ item.interface | default('') }}"
    direction: "{{ item.direction | default('in') }}"
    from_ip: "{{ item.from_ip | default('any') }}"
    to_ip: "{{ item.to_ip | default('any') }}"
    from_port: "{{ item.from_port | default('') }}"
    to_port: "{{ item.to_port | default('') }}"
    protocol: "{{ item.protocol | default('any') }}"
    route: "{{ item.route | default(omit) }}"
    log: "{{ item.log | default(false) }}"
    comment: "{{ item.comment | default(omit) }}"
  with_items: "{{ ufw_rules }}"
  notify:
    - Reload ufw

- name: Enable ufw and allow outgoing traffic
  community.general.ufw:
    state: enabled
    default: allow
    direction: outgoing
  notify:
    - Restart ufw

- name: Enable ufw and deny incomming traffic
  community.general.ufw:
    default: deny
    direction: incoming
  notify:
    - Restart ufw
