---

- name: Enable ufw
  ansible.builtin.systemd:
    name: ufw
    state: started
    enabled: true

- name: Restart ufw
  ansible.builtin.systemd:
    name: ufw
    state: restarted

- name: Reload ufw
  community.general.ufw:
    state: reloaded